name: EC2로 자동 배포하기

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH로 EC2 접속하기
        uses: appleboy/ssh-action@v1
        env:
          # ENV 라는 변수에 넣는다.
          ENV: ${{ secrets.ENV }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM_KEY}}
          envs: ENV
          script: |
            cd /home/ubuntu/fesi11-aws
            rm -rf .env
            git pull origin main
            echo "$ENV" > .env
            pm2 kill
            npm ci
            npm run build
            pm2 start npm --name "nextjs-app" -- start
